<?php

namespace AppBundle\Repository;

/**
 * AddUrlsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddUrlsRepository extends \Doctrine\ORM\EntityRepository
{
}
